### ISSUE TITLE
Funnel report only shows events for "unique users"

### ISSUE THREAD

**Issue by Than-DE** [Openpanel-dev/openpanel#72]
Hi, my event has been called multiple times by 3 unique users:

![CleanShot 2024-10-10 at 08 47 57@2x](https://github.com/user-attachments/assets/ade2a686-55d7-45cc-b045-bea21b6cd95e)

So if I create a funnel report and set it to "all events", it should show more than 3 events:
![CleanShot 2024-10-10 at 08 52 16@2x](https://github.com/user-attachments/assets/318d7579-5f25-40b4-a423-29d5a02a8979)

But it only shows 3. If i change to "unique users" it still says 3

![CleanShot 2024-10-10 at 08 52 40@2x](https://github.com/user-attachments/assets/25d890f0-9d01-47ca-b2c4-b4191a3f0f63)

**Comment by lindesvard** [comment]
This is actually correct. Funnels are based on sessions since I need a "common" parameter. It would be either `sessions` or `profiles`. 

The option you toggle does nothing and I'll remove the ability to change it when `Funnel` is the selected chart type.

If you just want to know how many `generate_quiz_attempt` you get I would suggest another chart type (eg. the line chart).
